# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-29 20:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='City_name')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add_time')),
                ('desc', models.CharField(max_length=200, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'City',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Organization_name')),
                ('desc', models.TextField(verbose_name='Description')),
                ('click_num', models.IntegerField(default=0, verbose_name='Click_num')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='Favourite_Numbers')),
                ('image', models.ImageField(upload_to='org/%Y/%m', verbose_name='Title_Images')),
                ('address', models.CharField(max_length=150, verbose_name='Address_name')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CityDict', verbose_name='City')),
            ],
            options={
                'verbose_name': 'CourseOrg',
                'verbose_name_plural': 'CourseOrg',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Teacher_name')),
                ('work_years', models.IntegerField(default=0, verbose_name='Work_year')),
                ('work_company', models.CharField(max_length=50, verbose_name='Work_company')),
                ('work_position', models.CharField(max_length=50, verbose_name='Work_position')),
                ('points', models.CharField(max_length=50, verbose_name='Points')),
                ('click_num', models.IntegerField(default=0, verbose_name='Click_num')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='Favourite_Numbers')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add_time')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teacher',
            },
        ),
    ]
