# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-02 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('org', 'Organization'), ('per', 'Personal'), ('col', 'College')], default='org', max_length=20, verbose_name='Org_category'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(upload_to='org/%Y/%m', verbose_name='Logo'),
        ),
    ]
