# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='famous', max_length=10, verbose_name='tag'),
        ),
    ]
