# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-29 20:36
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=200, verbose_name='Comments')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add_time')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'CourseComments',
                'verbose_name_plural': 'CourseComments',
            },
        ),
        migrations.CreateModel(
            name='UserAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='User_name')),
                ('mobile', models.CharField(max_length=10, verbose_name='Mobile')),
                ('course_name', models.CharField(max_length=50, verbose_name='Course_name')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add_time')),
            ],
            options={
                'verbose_name': 'UserAsk',
                'verbose_name_plural': 'UserAsk',
            },
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add_time')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'UserCourse',
                'verbose_name_plural': 'UserCourse',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_id', models.IntegerField(default=0, verbose_name='Fav_id')),
                ('fav_type', models.IntegerField(choices=[(1, 'Course'), (2, 'Organization'), (3, 'Teacher')], default=1, verbose_name='Fav_type')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add_time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'UserFavorite',
                'verbose_name_plural': 'UserFavorite',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0, verbose_name='UserMessage_id')),
                ('message', models.CharField(max_length=500, verbose_name='Message')),
                ('has_read', models.BooleanField(default=False, verbose_name='Has_read')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add_time')),
            ],
            options={
                'verbose_name': 'UserMessage',
                'verbose_name_plural': 'UserMessage',
            },
        ),
    ]
