# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-29 20:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='coursename')),
                ('desc', models.CharField(max_length=300, verbose_name='description')),
                ('detail', models.TextField(verbose_name='Detail')),
                ('degree', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('learn_time', models.IntegerField(default=0, verbose_name='Learn_time(Minutes)')),
                ('students', models.IntegerField(default=0, verbose_name='Amounts of students')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='Favourite_Numbers')),
                ('image', models.ImageField(upload_to='courses/%Y/%m', verbose_name='Title_Images')),
                ('click_nums', models.IntegerField(default=0, verbose_name='Click_Nums')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add_time')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Course',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Course_name')),
                ('download', models.FileField(upload_to='course/resource/%Y/%m', verbose_name='Download_file')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add_time')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'CourseResource',
                'verbose_name_plural': 'CourseResource',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Chapter_name')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add_time')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lesson',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Video_name')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add_time')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='Chapter')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Video',
            },
        ),
    ]
