# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseresource',
            options={'verbose_name': 'Resource', 'verbose_name_plural': 'Resource'},
        ),
    ]
