# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-06 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='Backend_develop', max_length=20, verbose_name='category'),
        ),
    ]
