# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-29 20:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('image', models.ImageField(upload_to='banner/%Y/%m', verbose_name='Banner_Pic')),
                ('url', models.URLField(verbose_name='VisitAddress')),
                ('index', models.IntegerField(default=100, verbose_name='Index')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add_Time')),
            ],
            options={
                'verbose_name': 'Banner_Pic',
                'verbose_name_plural': 'Banner_Pic',
            },
        ),
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='VerifyCode')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('send_type', models.CharField(choices=[('register', 'Register'), ('forget', 'Forget')], max_length=20)),
                ('send_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'EmailVerifyRecord',
                'verbose_name_plural': 'EmailVerifyRecord',
            },
        ),
    ]
