# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-30 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170329_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverifyrecord',
            options={'verbose_name': 'EmailVerify', 'verbose_name_plural': 'EmailVerify'},
        ),
    ]
