# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170330_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', 'Register'), ('forget', 'Forget'), ('update', 'Update')], max_length=20),
        ),
    ]
