# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170413_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateTimeField(null=True, verbose_name='Birthday'),
        ),
    ]
